import {
  pgTable,
  serial,
  integer,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

// Smart Advisor: AI-generated recommendations for holdings
// Each recommendation is generated by calling Gemini API with holding verdict data
// Note: watchlist_id references comparison_watchlist.id (created via SQL migration)
export const advisorRecommendationsTable = pgTable("advisor_recommendations", {
  id: serial("id").primaryKey(),
  watchlist_id: integer("watchlist_id").notNull(),
  recommendation_text: text("recommendation_text").notNull(),
  model_used: text("model_used").notNull(), // e.g. 'gemini-2.0-flash'
  generated_at: timestamp("generated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type AdvisorRecommendation = typeof advisorRecommendationsTable.$inferSelect;
export type InsertAdvisorRecommendation = typeof advisorRecommendationsTable.$inferInsert;
